// Code generated by wunderctl. DO NOT EDIT.

import type { OperationArgsWithInput, InternalClient as BaseClient } from '@wundergraph/sdk';
import {
  ContinentsResponse,
  CountriesResponse,
  CountriesInput,
  InternalCountriesInput,
  InjectedCountriesInput
} from './models';

export interface Queries {
  Continents: () => Promise<ContinentsResponse>;
  Countries: (
    options: OperationArgsWithInput<InternalCountriesInput>
  ) => Promise<CountriesResponse>;
}

export interface Mutations {
  mutations: {};
}

export interface InternalClient extends BaseClient<Queries, Mutations> {}
